### ISSUE TITLE
Parsing of mercurial diff file fails when containing add file or remove file.

### ISSUE THREAD

**Issue by drz1** [cloudbees/diff4j#1]
We encounter problems with Jenkins when using patch files generated with mercurial and fetched from ReviewBoard. The problem seems to be caused in ContextualPatch.java.

Here are two cases that causing Jenkins patch-plugin to fail:
1)
diff -r 8971ccb65fb5 -r dc9eb8e27f42 build/NewT/COMPONENTS
--- a/build/NewT/COMPONENTS    Fri Feb 28 15:49:11 2014 +0100
+++ /dev/null   Thu Jan 01 00:00:00 1970 +0000
@@ -1,1 +0,0 @@
-openbuild

2)
diff -r 8971ccb65fb5 -r dc9eb8e27f42 build/V/COMPONENTS
--- /dev/null   Thu Jan 01 00:00:00 1970 +0000
+++ b/build/V/COMPONENTS      Mon Mar 03 13:20:12 2014 +0100
@@ -0,0 +1,1 @@
+openbuild

Jenkins log:
...
Caused by: java.io.IOException: Failed to patch /home/hudson/workspace/node_review-linux32/a/build/NewT/COMPONENTS
    at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:229)
    at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:219)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2461)
    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:328)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
Caused by: com.cloudbees.diff.PatchException: Cannot apply hunk @@ 1
    at com.cloudbees.diff.ContextualPatch.applyHunk(ContextualPatch.java:228)
    at com.cloudbees.diff.ContextualPatch.applyPatch(ContextualPatch.java:155)
    at com.cloudbees.diff.ContextualPatch.patch(ContextualPatch.java:108)
    at org.jenkinsci.plugins.jenkinsreviewbot.ReviewboardParameterValue$ApplyTask.invoke(ReviewboardParameterValue.java:225)

**Comment by kohsuke** [comment]
Thanks to @hzilex and  @hgontijo this is now fixed
